name: Convert Web App to APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Android App (TWA)
      uses: corgito/twa-manifest-action@v1
      with:
        url: 'https://github.io'

    - name: Upload Finished APK
      uses: actions/upload-artifact@v4
      with:
        name: web-app-apk
        path: ./**/*.apk
